version: "3.3"
services:
  web:
    image: mrbond/tfo-httpd:0.1
    ports:
      - 80:80
    volumes:
      - /mnt/tfo-volume-01/sites/:/usr/local/apache2/sites/
      - /mnt/tfo-volume-01/tfo-docker-compose/src/dockerfiles/httpd/virtual-hosts/:/usr/local/apache2/virtual-hosts/
      - /mnt/tfo-volume-01/logs/:/usr/local/apache2/
      