version: "3.3"
services:
  web:
    image: mrbond/tfo-httpd:0.1
    networks:
      - public
    ports:
      - 80:80
    volumes:
      - /mnt/tfo-volume-01/sites/:/usr/local/apache2/sites/
      - /mnt/tfo-volume-01/tfo-docker-compose/src/dockerfiles/httpd/virtual-hosts/:/usr/local/apache2/virtual-hosts/
      - /mnt/tfo-volume-01/logs/:/usr/local/apache2/logs/
  grapevine-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=grapevine_rss
      - MYSQL_USER=grapevine
      - MYSQL_PASSWORD=${DB_PASSWD}
    networks:
      - private
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  grapevine-aggregator:
    image: mrbond/grapevine-rss-aggregator
    depends_on:
      - grapevine-mysql
    networks:
      - public
      - private
    ports:
      - 3000:3001
    environment:
      - CONFIG_ENV="prod"
      - DB_PASSWORD=${DB_PASSWD}
    command: ["run", "start"]
networks:
  public:
  private:
    internal: true
volumes:
  mysql: {}
