version: "3.3"
services:
  web:
    image: mrbond/tfo-httpd:0.9
    networks:
      - public
    ports:
      - 80:80
      - 443:443
    volumes:
      - /mnt/tfo-volume-01/sites/:/usr/local/apache2/sites/
      - /mnt/tfo-volume-01/tfo-docker-compose/src/dockerfiles/httpd/virtual-hosts/:/usr/local/apache2/virtual-hosts/
      - /mnt/tfo-volume-01/logs/:/usr/local/apache2/logs/
      - /mnt/tfo-volume-01/tfo-docker-compose/src/dockerfiles/letsencrypt/etc/live/:/usr/local/apache2/certs/
      - /mnt/tfo-volume-01/tfo-docker-compose/src/dockerfiles/letsencrypt/etc/archive/:/usr/local/apache2/archive/
    restart: always
networks:
  public:
  private:
    internal: true
